FROM ruby:2.5.8-slim-stretch

WORKDIR /usr/src/app

COPY Gemfile Gemfile.lock /usr/src/app/

RUN apt-get update && \
    apt-get install -y build-essential cron && \
    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5 && \
    echo "deb http://repo.mongodb.org/apt/debian stretch/mongodb-org/3.6 main" | tee /etc/apt/sources.list.d/mongodb-org-3.6.list && \
    apt-get update && \
    apt-get install -y mongodb-org-tools=3.6.17 && \
    gem install bundler -v "~> 2.0" && \
    bundle install && \
    apt-get remove -y build-essential && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*

COPY fs/ /

ENV BACKUP_DATA_PATH="/var/lib/backups" \
    BACKUP_TMP_PATH="/tmp/backup"

STOPSIGNAL SIGKILL

ENTRYPOINT [ "/usr/local/bin/entrypoint.sh" ]
